baseURL: "https://jpeckham.com/"
title: Joel Peckham
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  paperModCredit: false
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Joel Peckham
  description: "Joel Peckham's Software Portfolio & Personal Website"
  keywords: [Portfolio, Joel Peckham, Software Devloper, Software Engineer]
  # author: Joel Peckham
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon/favicon.ico"
    favicon16x16: "favicon/favicon-16x16.png"
    favicon32x32: "favicon/favicon-32x32.png"
    apple_touch_icon: "favicon/apple-touch-icon.png"
    safari_pinned_tab: "favicon/safari-pinned-tab.svg"

  label:
    text: "Joel Peckham"
    # icon: favicon/apple-touch-icon.png
    # iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Hello, friend!"
    Content: I'm a backend and AI developer looking for a home. <br /> Check out my projects below!
    # image: "https://source.unsplash.com/random/1920x1080"
    # imageAlt: "Home Page Image"

  socialIcons:
    - name: github
      url: "https://github.com/joelpeckham"
    - name: email
      url: "mailto:mail@jpeckham.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/joelpeckham/"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 10
    - identifier: about
      name: About me
      url: /about/
      weight: 20
    - identifier: My Github
      name: Github
      url: https://github.com/joelpeckham
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai


markup:
  goldmark:
    renderer:
      unsafe: true